import time
print("You wake up and find yourself in pitch black.")
time.sleep(1)
print("As your eyes begin to adjust to the dark you realize you are sitting in a clearing.")
time.sleep(2)
print("In front of you apears a friendly looking dwarf")
time.sleep(2)
print("He screams down to you shocking your senses ")
time.sleep(1)
print("\"HEELLOOO WELCOME DO YOU WANT TO HEAR ABOUT WHAT CARTER HAS DONE THIS WEEK\"")
nobreak = True
while(nobreak):
 	print("")
	time.sleep(3)
	print("Type an option")
	print("1. Hear what Carter has done and is going to do next week.")
	print("2. Go on adventure")
	print("3. Seduce the dwarf")
	print("4. Kill DwArF")
	code = int(input())
	if(code == 1):
		print("Carter finish the testing of the ALU last week. (You grow suspicious)")
		time.sleep(1)
		print("Carter is going to continue working with Thomas on the state machine")
		time.sleep(1)
		print("and begin working on the paper")
	elif(code == 2):
		print("You sprint as fast as you can away from the dwarf and into the forest")
		time.sleep(1)
		print("The pressure of running so quickly after being unconcious causes you to black out")
		time.sleep(1)
		print("You wake up and find yourself in pitch black.")
		time.sleep(1)
 		print("As your eyes begin to adjust to the dark you realize you are sitting in a clearing.")
		time.sleep(2)
		print("In front of you apears a friendly looking dwarf")
		time.sleep(2)
		print("He screams down to you shocking your senses ")
		time.sleep(1)
		print("\"HEELLOOO WELCOME DO YOU WANT TO HEAR ABOUT WHAT CARTER HAS DONE THIS WEEK\"")
		time.sleep(3)
	elif(code == 3):
		print("The dwarf feels unconfortable and so do you.")
	elif(code == 4):
		print("NO! Hes friendly!!")
